# SPDX-FileCopyrightText: 2026 James Harton <james.harton@alembic.com.au>
#
# SPDX-License-Identifier: Apache-2.0

%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "src/", "test/", "web/", "apps/*/lib/", "apps/*/src/"],
        # Generated by `mix localize.unit.gen_conversions`; its style is the
        # generator's, not ours, and any edit here is lost on regeneration.
        excluded: [~r"/_build/", ~r"/deps/", "lib/bb/unit/conversions.ex"]
      },
      strict: true
    }
  ]
}
