# SPDX-FileCopyrightText: 2026 James Harton <james.harton@alembic.com.au>
#
# SPDX-License-Identifier: Apache-2.0

[
  # `BB.Unit.Conversions` is generated by `mix localize.unit.gen_conversions`
  # and cannot be edited here. Its `parse_identifier/1` keeps a catch-all
  # clause for a parser failure that dialyzer proves unreachable — unknown
  # identifiers are rejected later, during decomposition, not by the parser.
  # Reported upstream; drop this entry once the generator stops emitting it.
  {"lib/bb/unit/conversions.ex", :pattern_match_cov}
]
