# SPDX-FileCopyrightText: 2025 James Harton
#
# SPDX-License-Identifier: Apache-2.0

spark_locals_without_parens = [
  actuator: 2,
  actuator: 3,
  allowed_states: 1,
  alpha: 1,
  argument: 2,
  argument: 3,
  axis: 0,
  axis: 1,
  blue: 1,
  box: 0,
  box: 1,
  collision: 0,
  collision: 1,
  color: 0,
  color: 1,
  command: 1,
  command: 2,
  controller: 2,
  controller: 3,
  cylinder: 0,
  cylinder: 1,
  damping: 1,
  default: 1,
  doc: 1,
  dynamics: 0,
  dynamics: 1,
  effort: 1,
  filename: 1,
  friction: 1,
  green: 1,
  group: 1,
  group: 2,
  handler: 1,
  height: 1,
  inertia: 0,
  inertia: 1,
  inertial: 0,
  inertial: 1,
  ixx: 1,
  ixy: 1,
  ixz: 1,
  iyy: 1,
  iyz: 1,
  izz: 1,
  joint: 1,
  joint: 2,
  limit: 0,
  limit: 1,
  link: 1,
  link: 2,
  lower: 1,
  mass: 1,
  material: 0,
  material: 1,
  max: 1,
  mesh: 0,
  mesh: 1,
  min: 1,
  name: 1,
  origin: 0,
  origin: 1,
  param: 1,
  param: 2,
  parameter_store: 1,
  pitch: 1,
  radius: 1,
  red: 1,
  registry_module: 1,
  registry_options: 1,
  required: 1,
  roll: 1,
  scale: 1,
  sensor: 2,
  sensor: 3,
  sphere: 0,
  sphere: 1,
  supervisor_module: 1,
  texture: 0,
  texture: 1,
  timeout: 1,
  type: 1,
  upper: 1,
  velocity: 1,
  visual: 0,
  visual: 1,
  x: 1,
  y: 1,
  yaw: 1,
  z: 1
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parems: spark_locals_without_parens
  ]
]
